use biblio;
-- Vider la base de données



-- Fill CATEGORIE_ABONNE
INSERT INTO CATEGORIE_ABONNE (ID_CATEGORIE) VALUES ('Etudiants');
INSERT INTO CATEGORIE_ABONNE (ID_CATEGORIE) VALUES ('Professionnels');
INSERT INTO CATEGORIE_ABONNE (ID_CATEGORIE) VALUES ('Enfants');
INSERT INTO CATEGORIE_ABONNE (ID_CATEGORIE) VALUES ('Employés');

-- Fill TYPE_OUVRAGE
INSERT INTO TYPE_OUVRAGE (ID_TYPE) VALUES ('Nouvelle');
INSERT INTO TYPE_OUVRAGE (ID_TYPE) VALUES ('Conte');
INSERT INTO TYPE_OUVRAGE (ID_TYPE) VALUES ('Mythe');
INSERT INTO TYPE_OUVRAGE (ID_TYPE) VALUES ('Legende');
INSERT INTO TYPE_OUVRAGE (ID_TYPE) VALUES ('Biographie');
INSERT INTO TYPE_OUVRAGE (ID_TYPE) VALUES ('Chronique');
INSERT INTO TYPE_OUVRAGE (ID_TYPE) VALUES ('Apologue');
INSERT INTO TYPE_OUVRAGE (ID_TYPE) VALUES ('Journal');
INSERT INTO TYPE_OUVRAGE (ID_TYPE) VALUES ('Roman');

-- Fill ABONNE
CALL INSERER_ABONNE_ALEATOIRE('César', 'Klein', '106665020', 'dijoux.josephine@gros.org', '81, avenue de Da Silva
76374 Laineboeuf');
CALL INSERER_ABONNE_ALEATOIRE('Salomé', 'Chevalier', '+33 (0)8 98 36 36 53', 'corinne37@ribeiro.com', 'rue Stéphanie Levy
77 640 Vaillantboeuf');
CALL INSERER_ABONNE_ALEATOIRE('Johan', 'Louis', '0357259645', 'aimee20@merle.com', '9, rue Aimée Labbe
20598 Martel');
CALL INSERER_ABONNE_ALEATOIRE('Jules', 'Chevalier', '+33 2 69 03 86 48', 'launay.yves@dbmail.com', '83, avenue Neveu
96611 Gautier-sur-Hubert');
CALL INSERER_ABONNE_ALEATOIRE('Lina', 'Lucas', '+33 6 23 47 29 20', 'denise84@gmail.com', '16, rue de Vasseur
75 024 Le Goff');
CALL INSERER_ABONNE_ALEATOIRE('Judith', 'Muller', '+33 (0)4 60 40 95 59', 'kpoirier@ifrance.com', 'chemin Langlois
48 264 ColasBourg');
CALL INSERER_ABONNE_ALEATOIRE('Jonas', 'Gaillard', '+33 3 96 99 67 88', 'llejeune@hardy.com', '2, rue Benoit
59 037 Lefort');
CALL INSERER_ABONNE_ALEATOIRE('Sophie', 'Guillot', '+33 6 71 26 13 36', 'michel.lombard@jacques.com', 'chemin de Faure
77824 MeunierVille');
CALL INSERER_ABONNE_ALEATOIRE('Daphné', 'Colin', '102162740', 'luce46@pruvost.com', '985, boulevard Berthelot
96857 Rousseau-la-Forêt');
CALL INSERER_ABONNE_ALEATOIRE('Victoria', 'Faure', '+33 (0)6 85 11 39 18', 'xvalette@tiscali.fr', '733, avenue Antoine
75892 Thomas');


-- Fill Auteur
INSERT INTO AUTEUR (NOM_AUTEUR, PRENOM_AUTEUR, TEL_AUTEUR, MAIL_AUTEUR, ADRESSE_AUTEUR)
VALUES ('Thomas', 'Deparrois', '+33 6 67 72 59 38', 'blacroix@yahoo.fr', '93, avenue de Gaillard
07699 Auger');
INSERT INTO AUTEUR (NOM_AUTEUR, PRENOM_AUTEUR, TEL_AUTEUR, MAIL_AUTEUR, ADRESSE_AUTEUR)
VALUES ('Arsène', 'Saligny', '09 39 99 59 87', 'laroche.celina@yahoo.fr', '329, rue David
11 316 Dupuis-les-Bains');
INSERT INTO AUTEUR (NOM_AUTEUR, PRENOM_AUTEUR, TEL_AUTEUR, MAIL_AUTEUR, ADRESSE_AUTEUR)
VALUES ('Léonard', 'Marchand', '+33 (0)8 23 08 50 23', 'tristan.gautier@yahoo.fr', '91, chemin Da Silva
45 869 Moreau');
INSERT INTO AUTEUR (NOM_AUTEUR, PRENOM_AUTEUR, TEL_AUTEUR, MAIL_AUTEUR, ADRESSE_AUTEUR)
VALUES ('Elsa', 'Melgares', '07 56 45 66 11', 'gmenard@carpentier.org', '80, place Hardy
96371 Launay-sur-Mer');
INSERT INTO AUTEUR (NOM_AUTEUR, PRENOM_AUTEUR, TEL_AUTEUR, MAIL_AUTEUR, ADRESSE_AUTEUR)
VALUES ('Camille', 'Blanchard', '01 49 80 64 09', 'martin.perrier@orange.fr', '656, avenue de Leveque
67 501 Gaillardnec');
INSERT INTO AUTEUR (NOM_AUTEUR, PRENOM_AUTEUR, TEL_AUTEUR, MAIL_AUTEUR, ADRESSE_AUTEUR)
VALUES ('Albane', 'Guerin', '02 01 72 60 79', 'elefort@voila.fr', '676, rue de Letellier
60857 Gilletnec');
INSERT INTO AUTEUR (NOM_AUTEUR, PRENOM_AUTEUR, TEL_AUTEUR, MAIL_AUTEUR, ADRESSE_AUTEUR)
VALUES ('Daniel', 'Saligny', '+33 8 05 83 12 59', 'bourgeois.zacharie@bernard.org', 'boulevard de Prevost
85 196 EtienneBourg');
INSERT INTO AUTEUR (NOM_AUTEUR, PRENOM_AUTEUR, TEL_AUTEUR, MAIL_AUTEUR, ADRESSE_AUTEUR)
VALUES ('Axelle', 'Leroy', '01 87 55 48 70', 'louise15@voila.fr', '99, impasse de Duval
02 244 Dubois-la-Forêt');
INSERT INTO AUTEUR (NOM_AUTEUR, PRENOM_AUTEUR, TEL_AUTEUR, MAIL_AUTEUR, ADRESSE_AUTEUR)
VALUES ('Ambre', 'Dufour', '01 47 85 46 01', 'bertrand.remy@richard.fr', '114, rue Xavier Guerin
51193 Durand-sur-Mer');
INSERT INTO AUTEUR (NOM_AUTEUR, PRENOM_AUTEUR, TEL_AUTEUR, MAIL_AUTEUR, ADRESSE_AUTEUR)
VALUES ('Jade', 'Lambrecq', '01 12 23 44 03', 'rmorvan@sfr.fr', 'rue Robert Didier
72075 Larocheboeuf');

-- Fill EDITEUR

INSERT INTO EDITEUR (NOM_EDITEUR, TEL_EDITEUR, MAIL_EDITEUR, ADRESSE_EDITEUR) 
VALUES ('Larousse','05 03 03 70 67','YoletteCharlebois@teleworm.us','79, rue Adolphe Wurtz');
INSERT INTO EDITEUR (NOM_EDITEUR, TEL_EDITEUR, MAIL_EDITEUR, ADRESSE_EDITEUR) 
VALUES ('Hachette','04 14 82 64 44','michele.coulon@live.com','275, rue Berger
19535 Masson');
INSERT INTO EDITEUR (NOM_EDITEUR, TEL_EDITEUR, MAIL_EDITEUR, ADRESSE_EDITEUR) 
VALUES ('Editis','09 88 45 58 72','sgaillard@yahoo.fr','rue Briand
49797 Maillard');
INSERT INTO EDITEUR (NOM_EDITEUR, TEL_EDITEUR, MAIL_EDITEUR, ADRESSE_EDITEUR) 
VALUES ('Gallimard','01 47 12 91 15','meyer.isabelle@tele2.fr','86, place de Alexandre
21 588 Costa');
INSERT INTO EDITEUR (NOM_EDITEUR, TEL_EDITEUR, MAIL_EDITEUR, ADRESSE_EDITEUR) 
VALUES ('Aparis','06 18 03 64 15','anais18@bourgeois.fr','88, avenue Fernandez
68 372 Pereiranec');
INSERT INTO EDITEUR (NOM_EDITEUR, TEL_EDITEUR, MAIL_EDITEUR, ADRESSE_EDITEUR) 
VALUES ('Albin Michel','06 53 12 89 50','odette11@sfr.fr','45, chemin Cordier
16813 Perez-sur-Mer');
INSERT INTO EDITEUR (NOM_EDITEUR, TEL_EDITEUR, MAIL_EDITEUR, ADRESSE_EDITEUR) 
VALUES ('Actes Sud','09 30 82 59 89','elodie.leclercq@ramos.net','6, boulevard Geneviève Gaudin
02 324 Vallee');
INSERT INTO EDITEUR (NOM_EDITEUR, TEL_EDITEUR, MAIL_EDITEUR, ADRESSE_EDITEUR) 
VALUES ('La Martiniere','01 10 23 08 46','chauvin.alphonse@coulon.net','663, impasse Louis Maurice
36959 Marynec');
INSERT INTO EDITEUR (NOM_EDITEUR, TEL_EDITEUR, MAIL_EDITEUR, ADRESSE_EDITEUR) 
VALUES ('Pocket','09 12 85 19 11','susanne.chevallier@didier.fr','60, rue Vincent
17147 Blondeldan');
INSERT INTO EDITEUR (NOM_EDITEUR, TEL_EDITEUR, MAIL_EDITEUR, ADRESSE_EDITEUR) 
VALUES ('Lumen','05 15 72 78 54','menard.noel@tiscali.fr','avenue Dominique Merle
96 270 Pichon');

-- Fill OUVRAGE

CALL INSERER_OUVRAGE_ALEATOIRE('Screams At The Slaves');
CALL INSERER_OUVRAGE_ALEATOIRE('Dwelling In The Castle');
CALL INSERER_OUVRAGE_ALEATOIRE('Sounds In The Shadows');
CALL INSERER_OUVRAGE_ALEATOIRE('Dead At The Universe');
CALL INSERER_OUVRAGE_ALEATOIRE('Whispers In My Friends');
CALL INSERER_OUVRAGE_ALEATOIRE('Pleasing My Family');
CALL INSERER_OUVRAGE_ALEATOIRE('Traces In The River');
CALL INSERER_OUVRAGE_ALEATOIRE('Avoiding My Husband');
CALL INSERER_OUVRAGE_ALEATOIRE('Songs Of My Wife');
CALL INSERER_OUVRAGE_ALEATOIRE('Mending The Darkness');

-- Fill ECRIT
INSERT INTO ECRIT(ID_OUVRAGE, ID_AUTEUR) VALUES (1,1);
INSERT INTO ECRIT(ID_OUVRAGE, ID_AUTEUR) VALUES (2,2);
INSERT INTO ECRIT(ID_OUVRAGE, ID_AUTEUR) VALUES (3,3);
INSERT INTO ECRIT(ID_OUVRAGE, ID_AUTEUR) VALUES (4,4);
INSERT INTO ECRIT(ID_OUVRAGE, ID_AUTEUR) VALUES (5,5);
INSERT INTO ECRIT(ID_OUVRAGE, ID_AUTEUR) VALUES (6,6);
INSERT INTO ECRIT(ID_OUVRAGE, ID_AUTEUR) VALUES (7,7);
INSERT INTO ECRIT(ID_OUVRAGE, ID_AUTEUR) VALUES (8,8);
INSERT INTO ECRIT(ID_OUVRAGE, ID_AUTEUR) VALUES (9,9);
INSERT INTO ECRIT(ID_OUVRAGE, ID_AUTEUR) VALUES (10,10);

-- Fill EMPRUNT
INSERT INTO EMPRUNTER(ID_ABONNE, ID_OUVRAGE, DATE_SORTIE, DATE_RETOUR) VALUES(1,1,curdate(), curdate());
INSERT INTO EMPRUNTER(ID_ABONNE, ID_OUVRAGE, DATE_SORTIE, DATE_RETOUR) VALUES(2,2,curdate(), curdate());
INSERT INTO EMPRUNTER(ID_ABONNE, ID_OUVRAGE, DATE_SORTIE, DATE_RETOUR) VALUES(3,3,curdate(), curdate());
INSERT INTO EMPRUNTER(ID_ABONNE, ID_OUVRAGE, DATE_SORTIE, DATE_RETOUR) VALUES(4,4,curdate(), curdate());
INSERT INTO EMPRUNTER(ID_ABONNE, ID_OUVRAGE, DATE_SORTIE, DATE_RETOUR) VALUES(5,5,curdate(), curdate());
INSERT INTO EMPRUNTER(ID_ABONNE, ID_OUVRAGE, DATE_SORTIE, DATE_RETOUR) VALUES(6,6,curdate(), curdate());
INSERT INTO EMPRUNTER(ID_ABONNE, ID_OUVRAGE, DATE_SORTIE, DATE_RETOUR) VALUES(7,7,curdate(), curdate());
INSERT INTO EMPRUNTER(ID_ABONNE, ID_OUVRAGE, DATE_SORTIE, DATE_RETOUR) VALUES(8,8,curdate(), curdate());
INSERT INTO EMPRUNTER(ID_ABONNE, ID_OUVRAGE, DATE_SORTIE, DATE_RETOUR) VALUES(9,9,curdate(), curdate());
INSERT INTO EMPRUNTER(ID_ABONNE, ID_OUVRAGE, DATE_SORTIE, DATE_RETOUR) VALUES(10,10,curdate(), curdate());
